# Generated by Django 5.0.4 on 2024-05-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subheading', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='')),
                ('link', models.URLField()),
                ('description2', models.TextField()),
                ('Author', models.CharField(max_length=255)),
            ],
        ),
    ]
