# Generated by Django 5.0.4 on 2024-05-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AryanApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collobrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('company_name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
            ],
        ),
    ]
