# Generated by Django 3.2.4 on 2024-05-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AryanApp', '0002_collobrate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collobrate',
            new_name='Services',
        ),
    ]
